/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiEditImageRouteImport } from './routes/api/edit-image'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiSnippetsRouteImport } from './routes/api/snippets'
import { Route as ApiWritePostRouteImport } from './routes/api/write-post'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppEditRouteImport } from './routes/app/edit'
import { Route as AppGenerateRouteImport } from './routes/app/generate'
import { Route as AppLibraryRouteImport } from './routes/app/library'
import { Route as AppSnippetsRouteImport } from './routes/app/snippets'
import { Route as AppWriteRouteImport } from './routes/app/write'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditImageRoute = ApiEditImageRouteImport.update({
  id: '/api/edit-image',
  path: '/api/edit-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnippetsRoute = ApiSnippetsRouteImport.update({
  id: '/api/snippets',
  path: '/api/snippets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWritePostRoute = ApiWritePostRouteImport.update({
  id: '/api/write-post',
  path: '/api/write-post',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEditRoute = AppEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGenerateRoute = AppGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSnippetsRoute = AppSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWriteRoute = AppWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/write-post': typeof ApiWritePostRoute
  '/app/edit': typeof AppEditRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/library': typeof AppLibraryRoute
  '/app/snippets': typeof AppSnippetsRoute
  '/app/write': typeof AppWriteRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/write-post': typeof ApiWritePostRoute
  '/app/edit': typeof AppEditRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/library': typeof AppLibraryRoute
  '/app/snippets': typeof AppSnippetsRoute
  '/app/write': typeof AppWriteRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/snippets': typeof ApiSnippetsRoute
  '/api/write-post': typeof ApiWritePostRoute
  '/app/edit': typeof AppEditRoute
  '/app/generate': typeof AppGenerateRoute
  '/app/library': typeof AppLibraryRoute
  '/app/snippets': typeof AppSnippetsRoute
  '/app/write': typeof AppWriteRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/snippets'
    | '/api/write-post'
    | '/app/edit'
    | '/app/generate'
    | '/app/library'
    | '/app/snippets'
    | '/app/write'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/snippets'
    | '/api/write-post'
    | '/app/edit'
    | '/app/generate'
    | '/app/library'
    | '/app/snippets'
    | '/app/write'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/snippets'
    | '/api/write-post'
    | '/app/edit'
    | '/app/generate'
    | '/app/library'
    | '/app/snippets'
    | '/app/write'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiEditImageRoute: typeof ApiEditImageRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiSnippetsRoute: typeof ApiSnippetsRoute
  ApiWritePostRoute: typeof ApiWritePostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit-image': {
      id: '/api/edit-image'
      path: '/api/edit-image'
      fullPath: '/api/edit-image'
      preLoaderRoute: typeof ApiEditImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snippets': {
      id: '/api/snippets'
      path: '/api/snippets'
      fullPath: '/api/snippets'
      preLoaderRoute: typeof ApiSnippetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/write-post': {
      id: '/api/write-post'
      path: '/api/write-post'
      fullPath: '/api/write-post'
      preLoaderRoute: typeof ApiWritePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/edit': {
      id: '/app/edit'
      path: '/edit'
      fullPath: '/app/edit'
      preLoaderRoute: typeof AppEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/generate': {
      id: '/app/generate'
      path: '/generate'
      fullPath: '/app/generate'
      preLoaderRoute: typeof AppGenerateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/snippets': {
      id: '/app/snippets'
      path: '/snippets'
      fullPath: '/app/snippets'
      preLoaderRoute: typeof AppSnippetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/write': {
      id: '/app/write'
      path: '/write'
      fullPath: '/app/write'
      preLoaderRoute: typeof AppWriteRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppEditRoute: typeof AppEditRoute
  AppGenerateRoute: typeof AppGenerateRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSnippetsRoute: typeof AppSnippetsRoute
  AppWriteRoute: typeof AppWriteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppEditRoute: AppEditRoute,
  AppGenerateRoute: AppGenerateRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSnippetsRoute: AppSnippetsRoute,
  AppWriteRoute: AppWriteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiEditImageRoute: ApiEditImageRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiSnippetsRoute: ApiSnippetsRoute,
  ApiWritePostRoute: ApiWritePostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
